### ISSUE TITLE
Error while testing the model

### ISSUE THREAD

**Issue by meghana99** [codeBlooded29/stackoverflow.com-answer-predictor#1]
python3 Test_2.py
0
0
Traceback (most recent call last):
  File "Test_2.py", line 21, in <module>
    res = clf.predict(X_test)
  File "/usr/local/lib/python3.7/site-packages/sklearn/tree/tree.py", line 416, in predict
    X = self._validate_X_predict(X, check_input)
  File "/usr/local/lib/python3.7/site-packages/sklearn/tree/tree.py", line 377, in _validate_X_predict
    X = check_array(X, dtype=DTYPE, accept_sparse="csr")
  File "/usr/local/lib/python3.7/site-packages/sklearn/utils/validation.py", line 552, in check_array
    "if it contains a single sample.".format(array))
ValueError: Expected 2D array, got 1D array instead:
array=[].
Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.

**Comment by codeBlooded29** [comment]
Wait I am looking into it.

**Comment by codeBlooded29** [comment]
Do you have "features_test1" & "labels_test1" binary files? Test_2.py script requires testing data i.e., these 2 files to validate its learning on training data against testing one.

**Comment by meghana99** [comment]
Yes, that’s generated after I run the feature generator.

**Comment by meghana99** [comment]
Training works perfectly fine.
Testing is where I get the error.

**Comment by codeBlooded29** [comment]
See, the training and testing are according to the classifier which you are using. Test_2.py is using Decision Tree Classifier, so the model trained binary files should also built by using the same classifier. This should help.

**Comment by meghana99** [comment]
How else will the files be generated ?

**Comment by meghana99** [comment]
Is the program running at your end?

**Comment by codeBlooded29** [comment]
Yes, it is running successfully at my end. Moreover you are getting 0s as length of two files. This should not be the case.

**Comment by codeBlooded29** [comment]
92640
92640
0.8402633851468049
Testing Successful!

<- Result

**Comment by meghana99** [comment]
That’s interesting!
Yes I am getting zero.
I believe that is because data is not being appended to features_test and
label_test.
Is it possible that u send me the files you are running on your computer?

**Comment by codeBlooded29** [comment]
Ok I will push to the repo.

**Comment by meghana99** [comment]
Hey Siddharth,

Thanks for pushing the files to repo.
But I guess the feature generation code file you are using is different too.
Can you push that too if possible ?


Thanks,
Meghana

**Comment by codeBlooded29** [comment]
I am also using the same file, as in the repository. The main fact is that you are not considering the amount of data you have and in which ratio you are dividing in training as testing dataset. According to this you have to set the count in FeatureVectorsGeneration.py. Don't use the given value as it is, set according to your needs.

**Comment by meghana99** [comment]
I am using the exact dataset as you are.

**Comment by codeBlooded29** [comment]
Not possible, I haven't uploaded any dataset (nearly 1 GB) for features generation in this repo.

**Comment by meghana99** [comment]
Yes. But I believe you got the dataset by running the sql query which you
have uploaded.

**Comment by codeBlooded29** [comment]
Running one time gives only 50K records, I ran it multiple times to get nearly 120K records.

**Comment by meghana99** [comment]
Do you mean you gave different limits each time? like 150000-200000 and
simliar?
So you integrated all the different csv files into one ?

**Comment by codeBlooded29** [comment]
Yes, I followed this approach then.

**Comment by meghana99** [comment]
rel module does not have relevantquestions attribute.
I am assuming this is the rel module you used https://pypi.org/project/rel/

**Comment by meghana99** [comment]
Rel module in predictor function seems to be not found. Can you please
clarify ?
